
#include "pointers.h"

type_free p_free;
type_lua_createtable p_lua_createtable;
type_lua_getfield p_lua_getfield;
type_lua_getglobal p_lua_getglobal;
type_lua_gettop p_lua_gettop;
type_lua_pcallk p_lua_pcallk;
type_lua_pushcclosure p_lua_pushcclosure;
type_lua_pushinteger p_lua_pushinteger;
type_lua_pushnil p_lua_pushnil;
type_lua_pushstring p_lua_pushstring;
type_lua_pushvalue p_lua_pushvalue;
type_lua_rawgeti p_lua_rawgeti;
type_lua_rawset p_lua_rawset;
type_lua_rawseti p_lua_rawseti;
type_lua_setglobal p_lua_setglobal;
type_lua_settop p_lua_settop;
type_lua_toboolean p_lua_toboolean;
type_lua_tointegerx p_lua_tointegerx;
type_lua_tolstring p_lua_tolstring;
type_lua_type p_lua_type;
type_luaL_error p_luaL_error;
type_luaL_loadfilex p_luaL_loadfilex;
type_luaL_ref p_luaL_ref;
type_malloc p_malloc;
